z5labs/bedrock

.github/workflows/build.yaml, .github/workflows/codeql.yaml
=> story(security): add codeql workflow

.github/dependabot.yml
=> story(build): add dependabot workflow

.github/workflows/build.yaml, .gitignore, .goreleaser.yaml, example/otlp/Containerfile, example/otlp/main.go, example/simple_http/Containerfile, example/simple_http/main.go, example/simple_queue/Containerfile, example/simple_queue/main.go, go.mod, go.sum, pkg/otelconfig/gcp.go, pkg/otelconfig/otelconfig.go, pkg/otelconfig/otlp.go, pkg/otelslog/otelslog.go, pkg/slogfield/slogfield.go
=> story(otel): implement otlp initializer

app.go, example/otlp/main.go, example/simple_http/main.go, example/simple_queue/main.go
=> story(app): make InitTracerProvider option functional by passing in config

go.mod, go.sum, grpc/grpc.go, http/http.go, pkg/noop/noop.go, queue/common_options.go, queue/queue.go, queue/sqs/common_options.go, queue/sqs/sqs.go, queue/sqs/sqs_test.go
=> story(queue): implement consumer for sqs

go.mod, go.sum, queue/pubsub/common_options.go, queue/pubsub/pubsub.go, queue/pubsub/pubsub_test.go
=> story(queue): provide a consumer implementation for cloud pubsub

http/http.go, http/http_test.go, pkg/health/health.go, pkg/health/health_test.go
=> story(http): add hooks for health checks

app.go
Changes:
- Added support to register finalizer
- Fixed issue with build context
Closes #28
=> story(app): add finalize lifecycle hooks

README.md, app.go, app_test.go, example/otlp/main.go, example/simple_http/main.go, example/simple_queue/main.go, go.mod, go.sum, grpc/grpc.go, grpc/grpc_test.go, http/http.go, http/http_test.go, queue/common_options.go, queue/pubsub/pubsub.go, queue/pubsub/pubsub_test.go, queue/queue.go, queue/sqs/sqs.go, queue/sqs/sqs_test.go
=> story(brand): rename to bedrock

pkg/slogfield/slogfield.go, pkg/slogfield/slogfield_test.go
=> story(slogfield): add plurals

queue/sqs/sqs.go, queue/sqs/sqsslog/sqsslog.go
=> story(sqsslog): create helpers to standardize log attributes related to sqs

.goreleaser.yaml, example/http2/Containerfile, example/http2/main.go, example/tls_http/Containerfile, example/tls_http/main.go, http/http.go, http/httpvalidate/validate.go, http/httpvalidate/validate_example_test.go, http/httpvalidate/validate_test.go
=> story(http): support tls and http2

grpc/grpc.go
=> story(grpc): support tls

.github/workflows/build.yaml, .github/workflows/coverage.yaml, README.md
=> story(docs): add labels to readme

README.md, pkg/otelslog/otelslog.go, pkg/otelslog/otelslog_test.go
=> story(otelslog): automatically add trace id and span id to log record

README.md, app.go, app_example_test.go, app_test.go, example/http2/main.go, example/otlp/main.go, example/simple_grpc/main.go, example/simple_http/main.go, example/simple_queue/main.go, example/tls_http/main.go, grpc/grpc_test.go
=> story(runtimebuilder): migrate bedrock.BuildContext to context.Context

README.md, app.go, app_example_test.go, app_test.go, example/http2/main.go, example/otlp/main.go, example/simple_grpc/main.go, example/simple_http/main.go, example/simple_queue/main.go, example/tls_http/main.go, pkg/lifecycle/lifecycle.go
=> story(bedrock): add prehook registration with build context

README.md, app.go, pkg/config/config.go, pkg/config/config_example_test.go, pkg/config/config_test.go
=> story(bedrock): support merging and overwriting configs

README.md, http/httpclient/client.go, http/httpclient/client_test.go
=> story(httpclient): add oauth transport options

.goreleaser.yaml, app.go, example/custom_framework/README.md, example/custom_framework/echo/Containerfile, example/custom_framework/echo/config.yaml, example/custom_framework/echo/main.go, example/custom_framework/echo/service/service.go, example/custom_framework/framework/base_config.yaml, example/custom_framework/framework/framework.go, go.mod
=> story(example): showcase a custom framework built with bedrock

README.md, pkg/config/config.go, pkg/config/config_test.go
=> story(config): need to render template before merging subsequent configs

README.md, pkg/otelconfig/otlp.go
=> story(otelconfig): use otlptracegrpc instead of grpc directly

.github/workflows/codeql.yaml, example/custom_framework/framework/framework.go, example/http2/main.go, example/otlp/main.go, example/simple_grpc/main.go, example/simple_http/main.go, example/simple_queue/main.go, example/tls_http/main.go, pkg/otelconfig/gcp.go, pkg/otelconfig/otelconfig.go, pkg/otelconfig/otlp.go
=> story(otelconfig): pass entire resource as functional option

.github/workflows/release.yaml, .goreleaser.yaml
=> story(release): create a publish workflow

.github/workflows/release.yaml
=> story(release): delete duplicate permission block

queue/pubsub/pubsub.go, queue/sqs/sqs.go
=> story(otelslog): do not wrap handlers passed to helper packages and runtimes

README.md
=> story(readme): add awesome go badge

README.md, queue/sqs/sqs.go, queue/sqs/sqsslog/sqsslog.go
=> story(sqs): add info log statements in batch delete processor

README.md, app.go, pkg/lifecycle/lifecycle.go
=> story(lifecycle): add a prebuild hook

README.md, example/custom_framework/echo/main.go, example/custom_framework/echo/service/service.go, example/custom_framework/framework/framework.go
=> story(example/custom_framework): update based on latest best practice

.github/workflows/coverage.yaml, README.md
=> story(coverage): add permissions to coverage workflow

README.md, example/custom_framework/framework/framework.go, example/simple_grpc/main.go, grpc/grpc.go, grpc/grpc_test.go, pkg/health/health.go, pkg/health/health_example_test.go, pkg/health/health_test.go
=> story(health): refactor package to export conjuction functions and basic toggle implementation

README.md, pkg/maskslog/doc.go, pkg/maskslog/maskslog.go, pkg/maskslog/maskslog_example_test.go, pkg/maskslog/maskslog_test.go, pkg/otelslog/otelslog_example_test.go
=> story(maskslog): implement slog.Handler with masking support

README.md, app.go, app_example_test.go, example/custom_framework/framework/framework.go, pkg/config/config.go, pkg/config/config_example_test.go, pkg/config/config_test.go, pkg/config/configtmpl/configtmpl.go, pkg/config/configtmpl/configtmpl_example_test.go, pkg/config/configtmpl/configtmpl_test.go
=> story(config): make template funcs a read option instead of being hardcoded

.github/workflows/build.yaml, .github/workflows/codeql.yaml, .github/workflows/coverage.yaml, .github/workflows/release.yaml, .goreleaser.yaml
=> story(issue-236): update github action workflows and goreleaser config version

rest/endpoint/endpoint.go, rest/endpoint/endpoint_test.go
=> story(issue-240): validate request body content type header

README.md, rest/endpoint/endpoint.go, rest/endpoint/endpoint_test.go, rest/endpoint/inject.go
=> story(issue-241): rest support custom response headers

README.md, rest/endpoint/endpoint.go, rest/endpoint/endpoint_test.go, rest/endpoint/inject.go, rest/endpoint/openapi.go, rest/endpoint/openapi_test.go
=> story(issue-242): rest inject path params for use in endpoint handler

README.md, example/simple_rest/echo/model.go, example/simple_rest/echo/service.go, rest/endpoint/endpoint.go, rest/endpoint/endpoint_test.go, rest/endpoint/openapi_test.go, rest/rest_example_test.go
=> story(issue-250): endpoint change handler interface to use references instead of values

README.md
=> story(issue-257): update readme based on new top level package api

README.md, pkg/appbuilder/doc.go, pkg/appbuilder/otel.go, pkg/appbuilder/otel_test.go
=> story(issue-267): appbuilder implement a middleware package for app builders

README.md, pkg/app/app.go, pkg/app/app_test.go
=> story(issue-271): app add middleware for recovering from panics in apprun

go.mod, go.sum, pkg/appbuilder/appbuilder.go, pkg/appbuilder/appbuilder_example_test.go, pkg/appbuilder/appbuilder_test.go, pkg/appbuilder/otel.go, pkg/appbuilder/otel_example_test.go, pkg/appbuilder/otel_test.go
=> story(issue-274): appbuilder add recover middleware

pkg/app/app.go, pkg/app/app_example_test.go, pkg/app/app_test.go, pkg/app/otel_example_test.go
=> story(issue-273): app do not ignore lifecycle hook errors in post run

rest/endpoint/endpoint.go, rest/endpoint/endpoint_test.go
=> story(issue-277): endpoint pass contextcontext to errorhandler

README.md, bedrock.go, bedrock_test.go, pkg/app/app.go, pkg/app/app_example_test.go, pkg/app/app_test.go, pkg/appbuilder/appbuilder.go, pkg/appbuilder/appbuilder_example_test.go, pkg/appbuilder/appbuilder_test.go
=> story(issue-282): bedrock recover from panic in run

example/custom_framework/framework/rest/rest.go, example/simple_rest/app/app.go, rest/rest.go, rest/rest_example_test.go, rest/rest_test.go
=> story(issue-281): add option for providing a custom net.Listener

rest/rest.go, rest/rest_test.go
=> story(issue-284): rest refactor openapi endpoint into rest.Option

README.md, rest/endpoint/endpoint.go, rest/endpoint/endpoint_test.go, rest/endpoint/validate.go
=> story(issue-279): endpoint validate path params

README.md, rest/rest.go, rest/rest_test.go
=> story(issue-291): rest use strings.TrimSuffix instead of strings.TrimRight

README.md, example/custom_framework/echo/endpoint/echo.go, example/custom_framework/framework/rest/operation.go, example/simple_rest/app/app.go, example/simple_rest/echo/model.go, rest/endpoint/endpoint.go, rest/endpoint/endpoint_test.go, rest/endpoint/openapi_test.go, rest/endpoint/request.go, rest/endpoint/request_test.go, rest/endpoint/response.go, rest/endpoint/response_test.go, rest/endpoint/validate.go, rest/rest_example_test.go
=> story(issue-298): endpoint move to explicit request and response interfaces

README.md, rest/endpoint/endpoint.go, rest/endpoint/endpoint_test.go, rest/endpoint/openapi_test.go, rest/endpoint/request.go, rest/endpoint/response.go, rest/rest_example_test.go
=> story(issue-300): endpoint.Request interface needs to read from http.Request directly instead of a io.Reader

README.md, rest/endpoint/endpoint.go, rest/endpoint/endpoint_test.go
=> story(issue-302): endpoint remove writebufpool due to potential oom

README.md
=> story(readme): update to reflect new minimal implementation

README.md, app/app.go, app/app_example_test.go, app/app_test.go, appbuilder/appbuilder.go, appbuilder/appbuilder_example_test.go, appbuilder/appbuilder_test.go, appbuilder/otel.go, internal/try/try.go, internal/try/try_test.go, lifecycle/lifecycle.go, lifecycle/lifecycle_example_test.go
=> story(issue-358): migrate the lifecycle middleware from app to appbuilder

README.md, appbuilder/appbuilder.go, appbuilder/appbuilder_test.go, appbuilder/otel.go, appbuilder/otel_test.go
=> story(issue-361): add interrupt on appbuilder middleware

.github/renovate.json, renovate.json
=> story(issue-377): update indirect deps

.devcontainer/devcontainer.json
=> story(issue-382): add devcontainer config

renovate.json
=> story(issue-385): add post update options

README.md, go.mod, go.sum, lifecycle/lifecycle.go, lifecycle/lifecycle_example_test.go
=> story(issue-406): provide helpers for closing on post run
